#-------------------------------
# Site Settings
title: Steph Buongiorno
logo: # You can add own logo. For example '/images/logo.png'.
#description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: light # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Author Settings
author:
  author__name: Steph Buongiorno
  #author__bio: Placeholder bio
  #author__avatar: '/images/01-1.jpg'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com"}
- {icon: "ion-logo-reddit", link: "https://www.reddit.com/"}
#- {icon: "ion-logo-facebook", link: "https://facebook.com"}
#- {icon: "ion-logo-instagram", link: "https://instagram.com"}
#- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
#- {icon: "ion-logo-youtube", link: "https://youtube.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
# I removed the hero title 

#    Steph Buongiorno, PhD, is a postdoctoral research fellow in data science and high-performance computing (HPC) at Emory University’s Department of Data and Decision Sciences. 
#    She is also the director of <a href="https://democracy-lab.github.io/" target="_blank" class="hero-link">Democracy Lab</a> and the development of the 
#    <a href="https://democracyviewer.com/" target="_blank" class="hero-link">Democracy Viewer</a>. 
#    Her transdisciplinary research produces new knowledge that extends beyond the boundaries of any single field by introducing new methods for interpreting texts, data, culture, and society. 
#    Her work has been published by Cambridge University Press, AAAI, and IEEE, and supported by the National Science Foundation (NSF), the National Endowment for the Humanities (NEH), and the National Institute of Justice (NIJ). She enjoys poetry, all sorts of sensory things, and quiet underwater worlds.

hero:
  hero__title: ""
  hero__description: |
    I am a postdoctoral fellow in Emory University's Data and Decision Sciences department, where I direct <a href="https://democracy-lab.github.io/" target="_blank" class="hero-link">Democracy Lab</a> and the development of the <a href="https://democracyviewer.com/" target="_blank" class="hero-link">Democracy Viewer</a>.
    <br><br>
    I am pioneering the emerging field of "Experimental Computational Humanities" (ECH), a design-based research paradigm that integrates digital humanities, experimental humanities, and computer science to foreground experimentation and tool-building as modes of producing knowledge. ECH recognizes that answering challenging questions requires lots of perspectives, which is why researching across traditional academic boundaries to learn from each other is essential, as is a willingness to experiment across both the arts and the sciences, guided by an open-minded spirit of possibility and discovery.
    <br><br>
    Digital history is a field in which design-based research is especially productive. Tools are epistemic instruments for producing and mediating knowledge and the design of digital infrastructure shapes what kinds of historical questions can be asked and answered, and how universities and communities can collaboratively build systems that support analysis and knowledge creation. 
    <br><br>
    Using a design-based research approach, my tools have told global history at unprecedented scale, modeling consensus and dissent across Wikipedia’s 355 languages to advance multi-scale analyses of globality, connectivity, and interrelatedness that were previously infeasible. My other project, Democracy Viewer, is a public-history web application that provides citizens and researchers with accessible text-mining tools to examine how democratic discourse has changed over time.
    <br><br>
    My transdisciplinary scholarship has appeared or is forthcoming with Cambridge University Press, Journal of Early American Studies, Journal of Digital History, Association for the Advancement of Artificial Intelligence (AAAI), and the Institute of Electrical and Electronics Engineers (IEEE). My research has been supported by the National Science Foundation (NSF), the National Endowment for the Humanities (NEH), and the National Institute of Justice (NIJ).
#    <a href="https://github.com/stephbuon" style="color: blue; text-decoration:underline"> Visit GitHub </a>
#   <a href="https://stephbuon.github.io/cv/buongiorno_cv.pdf" style="color: blue; text-decoration:underline"> Download CV</a>. 


#    <br><br> If my open source software has helped you in some way, consider supporting my work: 
#    <a href="https://buymeacoffee.com/stephbuon" target="_blank">
#      <img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" 
#           alt="Buy Me A Coffee" 
#           style="height: 50px !important;width: 217px !important;" >
#    </a>
#-------------------------------
# Newsletter
#mailchimp:  # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
#mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
#mailchimp__input__text: Subscribe here
#mailchimp__button__text: Get a new tip


#-------------------------------
# Gallery Footer Section
#gallery:
#  gallery__title: Gallery
#  gallery__columns: 3
#  gallery__images:
#    - alt: 'Rest'
#      url: '/images/100.jpg'
#    - alt: 'Lifestyle'
#      url: '/images/101.jpg'
#    - alt: 'Hobby'
#      url: '/images/102.jpg'
#    - alt: 'Notes'
#      url: '/images/103.jpg'
#    - alt: 'Rest'
#      url: '/images/104.jpg'
#    - alt: 'Hobby'
#      url: '/images/105.jpg'
#    - alt: 'Fashion'
#      url: '/images/106.jpg'
#    - alt: 'Notes'
#      url: '/images/107.jpg'
#    - alt: 'Rest'
#      url: '/images/108.jpg'


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contant form
  description: Menso comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Menso theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: demo-menca # Add your shortname for Disqus Comment. For example demo-menca

#collections:
#  animals:
#    output: true
#    permalink: /my-animal/:name


#-------------------------------
# Google Analytics
google-analytics: G-0D82J3B2PG, GT-MB882Q # UA-237078961-3


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


























